"use client";

import { createContext, useCallback, useContext, useMemo, useRef, useState, type ReactNode } from "react";
import { STORAGE_KEY, createDefaultAchievements, createDemoQuests, createInitialLifeQuestState, defaultStats } from "@/data/defaults";
import { getOccupationQuestPack } from "@/data/questPacks";
import { inferCityEchoCategory, pickAdventureQuote } from "@/data/adventureQuotes";
import { useLocalStorage } from "@/hooks/useLocalStorage";
import { appendRecommendationHistory, toggleUniqueId } from "@/lib/adventurePreferences";
import { addQuest, addQuestPack, completeMapLocation as completeMapLocationOperation, completeMicroAdventure as completeMicroAdventureOperation, completeQuest as completeQuestOperation, deleteQuest as deleteQuestOperation, updateQuest as updateQuestOperation } from "@/lib/questOperations";
import { normalizeCustomMapLocation } from "@/lib/mapLocations";
import { importLifeQuestState, migrateLifeQuestState } from "@/lib/stateMigration";
import { unlockSkillNode as unlockSkillNodeOperation } from "@/lib/skillTree";
import { createId } from "@/lib/utils";
import { categoryLabels } from "@/data/labels";
import type { CompletionFeedback, CompletionMood, GrowthFocus, LifeMomentMood, LifeStage, LifeQuestState, MapLocation, OccupationCategory, Quest, QuestDraft, Role, StudentStage } from "@/types";

interface OnboardingInput { name: string; lifeStage: LifeStage; studentStage?: StudentStage; role: Role; occupation: OccupationCategory; customOccupationName?: string; occupationSuggestion?: string; focuses: GrowthFocus[]; }
interface LifeQuestContextValue {
  state: LifeQuestState; isHydrated: boolean; onboard: (input: OnboardingInput) => void; addQuest: (draft: QuestDraft) => void; addOccupationQuestPack: (occupation: OccupationCategory) => number; updateQuest: (questId: string, draft: QuestDraft) => void; deleteQuest: (questId: string) => void;
  completeQuest: (questId: string) => void; completeMicroAdventure: (adventureId: string, draft: QuestDraft, note: string, mood: LifeMomentMood) => void; toggleFavoriteAdventure: (adventureId: string) => void; toggleSavedAdventure: (adventureId: string) => void; dismissAdventure: (adventureId: string) => void; showAdventure: (adventureId: string) => void; selectAdventure: (adventureId: string) => void; clearSelectedAdventure: () => void;
  completeMapLocation: (location: MapLocation) => void; addCustomMapLocation: (location: MapLocation) => void; updateCustomMapLocation: (location: MapLocation) => void; deleteCustomMapLocation: (locationId: string) => void; unlockSkillNode: (nodeId: string) => boolean;
  completionFeedback: CompletionFeedback | null; closeCompletionFeedback: () => void; saveCompletionExperience: (mood: CompletionMood | null, note: string) => void; removeSavedQuote: (savedQuoteId: string) => void; removeAdventureJournalEntry: (entryId: string) => void;
  completeBeginnerGuide: () => void; restartBeginnerGuide: () => void; resetAppData: () => void; restoreDemoData: () => void; exportData: () => string; importData: (rawJson: string) => { success: boolean; message: string };
}
const LifeQuestContext = createContext<LifeQuestContextValue | null>(null);

export function LifeQuestProvider({ children }: { children: ReactNode }) {
  const createInitial = useCallback(() => createInitialLifeQuestState(), []);
  const [state, setState, isHydrated] = useLocalStorage(STORAGE_KEY, createInitial, migrateLifeQuestState);
  const [completionFeedback, setCompletionFeedback] = useState<CompletionFeedback | null>(null);
  const handledFeedbackEventIds = useRef(new Set<string>());
  const showFeedback = useCallback((eventId: string, quest: Quest, canSaveJournal = true, rewardLabel?: string) => {
    if (handledFeedbackEventIds.current.has(eventId)) return;
    handledFeedbackEventIds.current.add(eventId);
    const category = inferCityEchoCategory(quest);
    const quote = pickAdventureQuote(category, state.recentAdventureQuoteIds);
    setState((current) => ({ ...current, recentAdventureQuoteIds: [...current.recentAdventureQuoteIds, quote.id].slice(-4) }));
    setCompletionFeedback({ eventId, quote, taskId: quest.id, taskName: quest.title, completedAt: quest.completedAt ?? new Date().toISOString(), category, questCategory: quest.category, expReward: quest.expReward, rewardLabel, canSaveJournal });
  }, [setState, state.recentAdventureQuoteIds]);
  const onboard = useCallback((input: OnboardingInput) => setState((current) => ({ ...current, occupationSuggestions: input.occupation === "custom" && input.customOccupationName?.trim() ? [...current.occupationSuggestions, { id: createId("occupation"), name: input.customOccupationName.trim(), note: input.occupationSuggestion?.trim() ?? "", createdAt: new Date().toISOString() }] : current.occupationSuggestions, profile: { id: createId("hero"), name: input.name.trim(), lifeStage: input.lifeStage, studentStage: input.lifeStage === "student" ? input.studentStage : undefined, role: input.role, occupation: input.occupation, customOccupationName: input.occupation === "custom" ? input.customOccupationName?.trim() : undefined, focus: input.focuses[0] ?? "learning", focuses: input.focuses.length ? input.focuses : ["learning"], exp: 0, level: 1, createdAt: new Date().toISOString() } })), [setState]);
  const addQuestCallback = useCallback((draft: QuestDraft) => setState((current) => addQuest(current, draft)), [setState]);
  const addOccupationQuestPack = useCallback((occupation: OccupationCategory) => { const pack = getOccupationQuestPack(occupation); if (!pack) return 0; const result = addQuestPack(state, pack.quests); if (result.added) setState((current) => addQuestPack(current, pack.quests).state); return result.added; }, [setState, state]);
  const updateQuest = useCallback((id: string, draft: QuestDraft) => setState((current) => updateQuestOperation(current, id, draft)), [setState]);
  const deleteQuest = useCallback((id: string) => setState((current) => deleteQuestOperation(current, id)), [setState]);
  const completeQuest = useCallback((id: string) => { const quest = state.quests.find((item) => item.id === id); if (!quest || quest.status === "completed") return; const next = completeQuestOperation(state, id); setState(next); const completed = next.quests.find((item) => item.id === id); if (completed) showFeedback(`quest:${id}:${completed.completedAt}`, completed, true, `+1 ${categoryLabels[completed.category]}`); }, [setState, showFeedback, state]);
  const completeMicroAdventure = useCallback((adventureId: string, draft: QuestDraft, note: string, mood: LifeMomentMood) => { const next = completeMicroAdventureOperation(state, adventureId, draft, note, mood); if (next === state) return; setState(next); const completed = next.quests.find((quest) => quest.status === "completed" && quest.title === draft.title && quest.completedAt && !state.quests.some((previous) => previous.id === quest.id)); if (completed) showFeedback(`micro:${completed.id}`, completed, true, `+1 ${categoryLabels[completed.category]}`); }, [setState, showFeedback, state]);
  const updateAdventureIds = useCallback((field: "favoriteAdventureIds" | "savedAdventureIds", id: string, action: "favorite" | "saved") => setState((current) => ({ ...current, [field]: toggleUniqueId(current[field], id), recommendationHistory: appendRecommendationHistory(current.recommendationHistory, id, action) })), [setState]);
  const toggleFavoriteAdventure = useCallback((id: string) => updateAdventureIds("favoriteAdventureIds", id, "favorite"), [updateAdventureIds]);
  const toggleSavedAdventure = useCallback((id: string) => updateAdventureIds("savedAdventureIds", id, "saved"), [updateAdventureIds]);
  const dismissAdventure = useCallback((id: string) => setState((current) => { const now = new Date().toISOString(); const found = current.dismissedAdventures.find((item) => item.adventureId === id); return { ...current, dismissedAdventures: found ? current.dismissedAdventures.map((item) => item.adventureId === id ? { ...item, dismissedAt: now, count: item.count + 1 } : item) : [...current.dismissedAdventures, { adventureId: id, dismissedAt: now, count: 1 }], recommendationHistory: appendRecommendationHistory(current.recommendationHistory, id, "dismissed", now) }; }), [setState]);
  const showAdventure = useCallback((id: string) => setState((current) => ({ ...current, recommendationHistory: appendRecommendationHistory(current.recommendationHistory, id, "shown") })), [setState]);
  const selectAdventure = useCallback((id: string) => setState((current) => ({ ...current, selectedAdventureId: id })), [setState]);
  const clearSelectedAdventure = useCallback(() => setState((current) => current.selectedAdventureId ? { ...current, selectedAdventureId: null } : current), [setState]);
  const completeMapLocation = useCallback((location: MapLocation) => { if (state.mapCompletions.includes(location.id)) return; const next = completeMapLocationOperation(state, location); setState(next); const completed = next.quests.find((quest) => quest.id === `map-${location.id}`); if (completed) showFeedback(`location:${location.id}`, completed, true, `+1 ${categoryLabels.exploration}`); }, [setState, showFeedback, state]);
  const addCustomMapLocation = useCallback((location: MapLocation) => setState((current) => { const normalized = normalizeCustomMapLocation(location); return normalized && !current.customMapLocations.some((item) => item.id === normalized.id) ? { ...current, customMapLocations: [normalized, ...current.customMapLocations] } : current; }), [setState]);
  const updateCustomMapLocation = useCallback((location: MapLocation) => setState((current) => { const normalized = normalizeCustomMapLocation(location); return normalized ? { ...current, customMapLocations: current.customMapLocations.map((item) => item.id === normalized.id ? normalized : item) } : current; }), [setState]);
  const deleteCustomMapLocation = useCallback((id: string) => setState((current) => ({ ...current, customMapLocations: current.customMapLocations.filter((item) => item.id !== id), mapCompletions: current.mapCompletions.filter((item) => item !== id) })), [setState]);
  const unlockSkillNode = useCallback((nodeId: string) => { const result = unlockSkillNodeOperation(state, nodeId); if (result.success) { setState(result.state); const now = new Date().toISOString(); showFeedback(`skill:${result.node.id}`, { id: `skill:${result.node.id}`, title: result.node.title, description: result.node.description, type: "hidden", category: result.node.category, occupation: "general", difficulty: "easy", expReward: 0, status: "completed", createdAt: now, completedAt: now, priority: "normal", dueDate: null, estimatedMinutes: null, recurrence: "none", subtasks: [], questChainId: null }, false, result.node.rewardTitle); } return result.success; }, [setState, showFeedback, state]);
  const closeCompletionFeedback = useCallback(() => setCompletionFeedback(null), []);
  const saveCompletionExperience = useCallback((mood: CompletionMood | null, note: string) => { if (!completionFeedback || !completionFeedback.canSaveJournal) return; const id = `journal:${completionFeedback.eventId}`; setState((current) => current.adventureJournal.some((item) => item.id === id) ? current : { ...current, adventureJournal: [{ id, taskId: completionFeedback.taskId, taskName: completionFeedback.taskName, completedAt: completionFeedback.completedAt, category: completionFeedback.category, mood, note: note.trim() || undefined, quoteId: completionFeedback.quote.id, quoteText: completionFeedback.quote.text, quoteSourceType: completionFeedback.quote.sourceType, quoteSourceStatus: completionFeedback.quote.sourceStatus, quoteSourceTitle: completionFeedback.quote.sourceTitle, quoteSourceUrl: completionFeedback.quote.sourceUrl, quoteGame: completionFeedback.quote.game, quoteSkin: completionFeedback.quote.skin, quoteSpeaker: completionFeedback.quote.speaker, quoteAuthor: completionFeedback.quote.author, quoteWork: completionFeedback.quote.work, quoteDynasty: completionFeedback.quote.dynasty, quoteNote: completionFeedback.quote.note, expReward: completionFeedback.expReward, rewardLabel: completionFeedback.rewardLabel }, ...current.adventureJournal] }); setCompletionFeedback(null); }, [completionFeedback, setState]);
  const removeSavedQuote = useCallback((id: string) => setState((current) => ({ ...current, savedQuotes: current.savedQuotes.filter((item) => item.id !== id) })), [setState]);
  const removeAdventureJournalEntry = useCallback((id: string) => setState((current) => ({ ...current, adventureJournal: current.adventureJournal.filter((item) => item.id !== id) })), [setState]);
  const completeBeginnerGuide = useCallback(() => setState((current) => ({ ...current, userSettings: { ...current.userSettings, tutorialCompletedAt: new Date().toISOString() } })), [setState]);
  const restartBeginnerGuide = useCallback(() => setState((current) => ({ ...current, userSettings: { ...current.userSettings, tutorialCompletedAt: null } })), [setState]);
  const resetAppData = useCallback(() => setState(createInitialLifeQuestState()), [setState]);
  const restoreDemoData = useCallback(() => setState((current) => ({ ...createInitialLifeQuestState(), profile: current.profile ? { ...current.profile, exp: 0, level: 1 } : null, quests: createDemoQuests(), stats: { ...defaultStats }, achievements: createDefaultAchievements(), occupationSuggestions: current.occupationSuggestions })), [setState]);
  const exportData = useCallback(() => JSON.stringify(state, null, 2), [state]);
  const importData = useCallback((rawJson: string) => { const result = importLifeQuestState(rawJson); if (!result.success) return { success: false, message: "匯入失敗：請選擇有效的 Life Quest Map JSON 檔。" }; setState(result.state); return { success: true, message: "資料已匯入並完成遷移。" }; }, [setState]);
  const value = useMemo(() => ({ state, isHydrated, onboard, addQuest: addQuestCallback, addOccupationQuestPack, updateQuest, deleteQuest, completeQuest, completeMicroAdventure, toggleFavoriteAdventure, toggleSavedAdventure, dismissAdventure, showAdventure, selectAdventure, clearSelectedAdventure, completeMapLocation, addCustomMapLocation, updateCustomMapLocation, deleteCustomMapLocation, unlockSkillNode, completionFeedback, closeCompletionFeedback, saveCompletionExperience, removeSavedQuote, removeAdventureJournalEntry, completeBeginnerGuide, restartBeginnerGuide, resetAppData, restoreDemoData, exportData, importData }), [state, isHydrated, onboard, addQuestCallback, addOccupationQuestPack, updateQuest, deleteQuest, completeQuest, completeMicroAdventure, toggleFavoriteAdventure, toggleSavedAdventure, dismissAdventure, showAdventure, selectAdventure, clearSelectedAdventure, completeMapLocation, addCustomMapLocation, updateCustomMapLocation, deleteCustomMapLocation, unlockSkillNode, completionFeedback, closeCompletionFeedback, saveCompletionExperience, removeSavedQuote, removeAdventureJournalEntry, completeBeginnerGuide, restartBeginnerGuide, resetAppData, restoreDemoData, exportData, importData]);
  return <LifeQuestContext.Provider value={value}>{children}</LifeQuestContext.Provider>;
}
export function useLifeQuest() { const context = useContext(LifeQuestContext); if (!context) throw new Error("useLifeQuest must be used inside LifeQuestProvider."); return context; }
