"use client";

import { CalendarBlank, CheckCircle, Clock, Lightning, PencilSimple, Scroll, Target, Trash } from "@phosphor-icons/react";
import { categoryLabels, difficultyLabels, occupationLabels, questTypeLabels } from "@/data/labels";
import { getDueStatus, getSubtaskProgress } from "@/lib/questSchedule";
import type { Quest } from "@/types";

interface QuestCardProps { quest: Quest; featured?: boolean; onComplete?: (questId: string) => void; onEdit?: (quest: Quest) => void; onDelete?: (questId: string) => void; }
const priorityLabels = { high: "高優先", normal: "普通", low: "低優先" };
const dueLabels = { today: "今天到期", overdue: "已逾期", upcoming: "即將到期", none: "未設定截止日" };

export function QuestCard({ quest, featured = false, onComplete, onEdit, onDelete }: QuestCardProps) {
  const isCompleted = quest.status === "completed";
  const dueStatus = getDueStatus(quest);
  const progress = getSubtaskProgress(quest);
  return <article className={`relative overflow-hidden rounded-lg border transition ${featured ? "border-emerald-300/35 bg-[linear-gradient(145deg,rgba(16,185,129,0.18),rgba(9,9,11,0.76))] p-5 shadow-[0_24px_80px_rgba(0,0,0,0.24)]" : "border-white/10 bg-zinc-900/70 p-4"} ${isCompleted ? "opacity-70" : ""}`}><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-emerald-300/60 to-transparent" />
    <div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-lg border border-emerald-300/20 bg-emerald-300/10">{isCompleted ? <CheckCircle className="size-6 text-emerald-200" weight="fill" /> : <Scroll className="size-6 text-emerald-200" weight="duotone" />}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge label={questTypeLabels[quest.type]} accent /><Badge label={categoryLabels[quest.category]} /><Badge label={priorityLabels[quest.priority]} /><Badge label={difficultyLabels[quest.difficulty]} /></div><h3 className={`mt-3 font-black leading-snug text-zinc-50 ${featured ? "text-2xl" : "text-lg"}`}>{quest.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-300">{quest.description}</p></div></div><div className="shrink-0 text-right"><div className="inline-flex items-center gap-1 rounded-lg border border-emerald-300/20 bg-zinc-950/60 px-3 py-2 text-sm font-black text-emerald-100"><Lightning className="size-4" weight="fill" />{quest.expReward}</div><p className="mt-1 text-xs text-zinc-500">EXP</p></div></div>
    <div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-zinc-400"><span className={`inline-flex items-center gap-1.5 ${dueStatus === "overdue" ? "text-red-200" : dueStatus === "today" ? "text-amber-200" : ""}`}><CalendarBlank className="size-4" />{quest.dueDate ? `${dueLabels[dueStatus]} · ${quest.dueDate}` : dueLabels.none}</span>{quest.estimatedMinutes ? <span className="inline-flex items-center gap-1.5"><Clock className="size-4" />約 {quest.estimatedMinutes} 分鐘</span> : null}<span>{occupationLabels[quest.occupation]}</span>{quest.recurrence !== "none" ? <span className="text-emerald-100">{quest.recurrence === "daily" ? "每日重複" : "每週重複"}</span> : null}</div>
    {progress.total ? <div className="mt-4 rounded-lg bg-white/[0.04] p-3"><div className="flex items-center justify-between gap-3 text-sm"><span className="inline-flex items-center gap-1.5 font-bold text-zinc-200"><Target className="size-4 text-emerald-200" />子任務 {progress.completed} / {progress.total}</span><span className="font-bold text-emerald-100">{progress.percentage}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[0.08]"><div className="h-full rounded-full bg-emerald-300" style={{ width: `${progress.percentage}%` }} /></div></div> : null}
    <div className="mt-5 flex flex-wrap items-center gap-2">{onComplete ? <button type="button" onClick={() => onComplete(quest.id)} disabled={isCompleted} className={`rounded-lg px-4 py-2 text-sm font-black transition active:translate-y-px ${isCompleted ? "cursor-not-allowed bg-zinc-800 text-zinc-500" : "bg-emerald-300 text-zinc-950 hover:bg-emerald-200"}`}>{isCompleted ? "已完成" : "完成並獲得 EXP"}</button> : null}{onEdit && !isCompleted ? <button type="button" onClick={() => onEdit(quest)} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm font-bold text-zinc-200 transition hover:border-emerald-300/30 hover:text-emerald-100 active:translate-y-px"><PencilSimple className="size-4" />編輯</button> : null}{onDelete && !isCompleted ? <button type="button" onClick={() => onDelete(quest.id)} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm font-bold text-zinc-300 transition hover:border-red-300/30 hover:text-red-100 active:translate-y-px"><Trash className="size-4" />刪除</button> : null}</div>
  </article>;
}
function Badge({ label, accent = false }: { label: string; accent?: boolean }) { return <span className={`rounded-md border px-2 py-1 text-xs ${accent ? "border-emerald-300/20 bg-emerald-300/10 font-bold text-emerald-100" : "border-white/10 bg-white/[0.04] text-zinc-300"}`}>{label}</span>; }
