"use client";

import { ArrowLeft, CalendarBlank, ChartBar, Fire, Lightning, Sparkle } from "@phosphor-icons/react";
import { categoryLabels } from "@/data/labels";
import { formatLocalShortDate, getCategoryActivity, getRecentDayActivity, getRecentLifeMoments, getWeekActivity } from "@/lib/activityStats";
import type { LifeQuestState } from "@/types";

export function HistoryPanel({ state, onBack }: { state: LifeQuestState; onBack: () => void }) {
  const heatmap = getRecentDayActivity(state.quests);
  const week = getWeekActivity(state.quests);
  const categories = getCategoryActivity(state.quests);
  const moments = getRecentLifeMoments(state.lifeMoments);
  const hasActivity = heatmap.some((day) => day.completedCount > 0) || moments.length > 0;
  const heatMax = Math.max(1, ...heatmap.map((day) => day.completedCount));
  const categoryMax = Math.max(1, ...categories.map((item) => item.count));

  return <div className="space-y-5">
    <header className="flex items-start gap-3"><button type="button" onClick={onBack} aria-label="返回個人檔案" className="mt-1 grid size-10 place-items-center rounded-lg border border-white/10 text-zinc-200 transition hover:border-emerald-300/40 hover:text-emerald-100 active:translate-y-px"><ArrowLeft className="size-5" /></button><div><p className="text-sm font-semibold text-emerald-200">Adventure History</p><h1 className="mt-1 text-3xl font-black text-zinc-50">冒險歷史</h1><p className="mt-2 text-sm leading-6 text-zinc-400">把完成過的任務與留下的生命片段，整理成你的成長軌跡。</p></div></header>
    {!hasActivity ? <section className="game-card p-6 text-center sm:p-10"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-emerald-300/10 text-emerald-200"><Sparkle className="size-7" weight="fill" /></div><h2 className="mt-5 text-2xl font-black text-zinc-50">第一段紀錄，還在等你開始</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-zinc-400">完成任務或微冒險後，這裡會顯示你的 30 天活動、類別分布與生命片段時間軸。</p><button type="button" onClick={onBack} className="mt-5 rounded-lg bg-emerald-300 px-4 py-3 text-sm font-bold text-zinc-950 transition hover:bg-emerald-200 active:translate-y-px">返回個人檔案</button></section> : <>
      <section className="grid gap-3 sm:grid-cols-2"><Summary icon={<CalendarBlank className="size-5" weight="duotone" />} label="近 7 天完成" value={`${week.reduce((total, day) => total + day.completedCount, 0)} 項`} /><Summary icon={<Lightning className="size-5" weight="fill" />} label="近 7 天 EXP" value={`${week.reduce((total, day) => total + day.expEarned, 0)} EXP`} /></section>
      <section className="game-card p-4 sm:p-5"><div className="flex items-center gap-2"><Fire className="size-5 text-emerald-200" weight="fill" /><div><h2 className="text-xl font-black text-zinc-50">近 30 天活動</h2><p className="mt-1 text-sm text-zinc-400">色塊越亮，代表當天完成的任務越多。</p></div></div><div className="mt-5 grid grid-cols-5 gap-2 sm:grid-cols-10">{heatmap.map((day) => <div key={day.date} className="min-w-0"><div title={`${day.date}: ${day.completedCount} 項`} className={`aspect-square rounded-md border border-emerald-200/10 ${day.completedCount === 0 ? "bg-white/[0.035]" : day.completedCount / heatMax > 0.66 ? "bg-emerald-300" : day.completedCount / heatMax > 0.33 ? "bg-emerald-400/65" : "bg-emerald-500/35"}`} /><p className="mt-1 truncate text-center text-[10px] text-zinc-500">{formatLocalShortDate(day.date)}</p></div>)}</div></section>
      <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="game-card p-4 sm:p-5"><div className="flex items-center gap-2"><ChartBar className="size-5 text-emerald-200" weight="duotone" /><div><h2 className="text-xl font-black text-zinc-50">類別分布</h2><p className="mt-1 text-sm text-zinc-400">完成任務累積的成長方向。</p></div></div><div className="mt-5 space-y-3">{categories.map((item) => <div key={item.category}><div className="flex justify-between gap-3 text-sm"><span className="font-bold text-zinc-200">{categoryLabels[item.category]}</span><span className="text-emerald-100">{item.count} 項</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-emerald-300" style={{ width: `${(item.count / categoryMax) * 100}%` }} /></div></div>)}</div></div><div className="game-card p-4 sm:p-5"><h2 className="text-xl font-black text-zinc-50">連續冒險</h2><p className="mt-2 text-sm leading-6 text-zinc-400">讓每天的小進展，慢慢成為穩定的節奏。</p><div className="mt-6 grid grid-cols-2 gap-3"><Summary icon={<Fire className="size-5" weight="fill" />} label="目前" value={`${state.streak.current} 天`} /><Summary icon={<Sparkle className="size-5" weight="fill" />} label="最長" value={`${state.streak.longest} 天`} /></div></div></section>
      <section className="game-card p-4 sm:p-5"><h2 className="text-xl font-black text-zinc-50">生命片段時間軸</h2><p className="mt-1 text-sm text-zinc-400">微冒險留下的感受與筆記。</p>{moments.length ? <ol className="mt-5 space-y-3">{moments.map((moment) => <li key={moment.id} className="relative pl-5 before:absolute before:left-0 before:top-2 before:size-2 before:rounded-full before:bg-emerald-300"><p className="text-sm font-bold text-zinc-100">{moment.adventureName}</p><p className="mt-1 text-xs text-emerald-100">{new Date(moment.completedAt).toLocaleString()}</p>{moment.note ? <p className="mt-2 text-sm leading-6 text-zinc-300">{moment.note}</p> : <p className="mt-2 text-sm text-zinc-500">未留下文字筆記</p>}</li>)}</ol> : <div className="mt-5 rounded-lg bg-white/[0.04] p-4 text-sm leading-6 text-zinc-400">目前還沒有生命片段。完成一次微冒險並留下感受後，時間軸會在這裡展開。</div>}</section>
    </>}
  </div>;
}

function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article className="rounded-lg border border-white/10 bg-zinc-950/50 p-4"><div className="flex items-center gap-2 text-emerald-200">{icon}<p className="text-xs font-bold text-zinc-400">{label}</p></div><p className="mt-3 text-2xl font-black text-zinc-50">{value}</p></article>; }
